# funny_file.py

# Define mappings for keywords
KEYWORD_MAP = {
    'False': 'Fawlse',
    'None': 'Nyonya',
    'True': 'Twue',
    'and': 'anwd',
    'as': 'asy',
    'assert': 'asswert',
    'async': 'asywync',
    'await': 'awaiwt',
    'break': 'bweak',
    'class': 'cwassie',
    'continue': 'conwtinwue',
    'def': 'dewf',
    'del': 'dewlete',
    'elif': 'elifw',
    'else': 'elswe',
    'except': 'excwept',
    'finally': 'finyawwy',
    'for': 'fowr',
    'from': 'fwom',
    'global': 'gwobawl',
    'if': 'ifflie',
    'import': 'impowt',
    'in': 'innya',
    'is': 'ishy',
    'lambda': 'lambdwah',
    'nonlocal': 'nonwy',
    'not': 'nwope',
    'or': 'owr',
    'pass': 'pawss',
    'raise': 'waiwise',
    'return': 'weeturn',
    'try': 'twry',
    'while': 'whiwile',
    'with': 'withie',
    'yield': 'yiewldy',
    'bool': 'baka',
    'string': 'pwease',
    'int': 'nuu',
    'float': 'kawaii',
    'list': 'nyan',
}

# Define mappings for built-in functions
BUILTIN_MAP = {
    'abs': 'awbsies',
    'all': 'aww',
    'any': 'anyo',
    'ascii': 'ascwe',
    'bin': 'biny',
    'bool': 'booww',
    'bytearray': 'bytwearies',
    'bytes': 'bytwes',
    'callable': 'cawwawbe',
    'chr': 'chaw',
    'classmethod': 'cwasmwod',
    'compile': 'compwye',
    'complex': 'compwexie',
    'delattr': 'dewatties',
    'dict': 'diction',
    'dir': 'diw',
    'divmod': 'diwmodie',
    'enumerate': 'enumewate',
    'eval': 'evaw',
    'exec': 'exie',
    'filter': 'fiwtuw',
    'float': 'fwoaty',
    'format': 'fowmat',
    'frozenset': 'fwowzenset',
    'getattr': 'gewtatties',
    'globals': 'gwobwals',
    'hasattr': 'haswatties',
    'hash': 'hush',
    'help': 'hewlp',
    'hex': 'hexie',
    'id': 'idy',
    'input': 'inpuwt',
    'int': 'inty',
    'isinstance': 'isyance',
    'issubclass': 'issubcwaas',
    'iter': 'itw',
    'len': 'leny',
    'list': 'wistie',
    'locals': 'wocals',
    'map': 'mapy',
    'max': 'maxx',
    'memoryview': 'memowyview',
    'min': 'minnie',
    'next': 'nextie',
    'object': 'objwect',
    'oct': 'octy',
    'open': 'owpen',
    'ord': 'owd',
    'pow': 'powie',
    'print': 'pwint',
    'property': 'pwopwty',
    'range': 'wange',
    'repr': 'wepw',
    'reversed': 'wevewse',
    'round': 'woundie',
    'set': 'setw',
    'setattr': 'sewtatties',
    'slice': 'swice',
    'sorted': 'sowted',
    'staticmethod': 'statwmowd',
    'str': 'stwie',
    'sum': 'swum',
    'super': 'supw',
    'tuple': 'tuwple',
    'type': 'typie',
    'vars': 'vaws',
    'zip': 'ziwp',
}

# Swapping keys and values
KEYWORD_MAP = {v: k for k, v in KEYWORD_MAP.items()}
BUILTIN_MAP = {v: k for k, v in BUILTIN_MAP.items()}

combined_map = {**KEYWORD_MAP, **BUILTIN_MAP}