# Keywords
# False: Fawlse
# None: Nyonya
# True: Twue
# and: anwd
# as: asy
# assert: asswert
# async: asywync
# await: awaiwt
# break: bweak
# class: cwassie
# continue: conwtinwue
# def: dewf
# del: dewlete
# elif: elifw
# else: elswe
# except: excwept
# finally: finyawwy
# for: fowr
# from: fwom
# global: gwobawl
# if: ifflie
# import: impowt
# in: innya
# is: ishy
# lambda: lambdwah
# nonlocal: nonwy
# not: nwope
# or: owr
# pass: pawss
# raise: waiwise
# return: weeturn
# try: twry
# while: whiwile
# with: withie
# yield: yiewldy
# baka: bool
# pwease: string
# nuu: int
# kawaii: float
# nyan: array/list

KEYYWOwOWD_WIST = ['Fawlse', 'Nyonya', 'Twue', 'anwd', 'asy', 'asswert', 'asywync', 'awaiwt', 'bweak', 'cwassie', 'conwtinwue', 'dewf', 'dewlete', 'elifw', 'elswe', 'excwept', 'finyawwy', 'fowr', 'fwom', 'gwobawl', 'iffie', 'impowt', 'innya', 'ishy', 'lambdwah', 'nonwy', 'nwope', 'owr', 'pawss', 'waiwise', 'weeturn', 'twry', 'whiwile', 'withie', 'yiewldy', 'baka', 'pwease', 'nuu', 'kawaii', 'nyan', 'switchee', 'cwaise', 'cawtch']

# Builtins
# abs: awbsies
# all: aww
# any: anyo
# ascii: ascwe
# bin: biny
# bool: booww
# bytearray: bytwearies
# bytes: bytwes
# callable: cawwawbe
# chr: chaw
# classmethod: cwasmwod
# compile: compwye
# complex: compwexie
# delattr: dewatties
# dict: diction
# dir: diw
# divmod: diwmodie
# enumerate: enumewate
# eval: evaw
# exec: exie
# filter: fiwtuw
# float: fwoaty
# format: fowmat
# frozenset: fwowzenset
# getattr: gewtatties
# globals: gwobwals
# hasattr: haswatties
# hash: hush
# help: hewlp
# hex: hexie
# id: idy
# input: inpuwt
# int: inty
# isinstance: isyance
# issubclass: issubcwaas
# iter: itw
# len: leny
# list: wistie
# locals: wocals
# map: mapy
# max: maxx
# memoryview: memowyview
# min: minnie
# next: nextie
# object: objwect
# oct: octy
# open: owpen
# ord: owd
# pow: powie
# print: pwint
# property: pwopwty
# range: wange
# repr: wepw
# reversed: wevewse
# round: woundie
# set: setw
# setattr: sewtatties
# slice: swice
# sorted: sowted
# staticmethod: statwmowd
# str: stwie
# sum: swum
# super: supw
# tuple: tuwple
# type: typie
# vars: vaws
# zip: ziwp

bUwUiwtin_fOwOnctwions_nyans = ['awbsies', 'aww', 'anyo', 'ascwe', 'biny', 'booww', 'bytwearies', 'bytwes', 'cawwawbe', 'chaw', 'cwasmwod', 'compwye', 'compwexie', 'dewatties', 'diction', 'diw', 'diwmodie', 'enumewate', 'evaw', 'exie', 'fiwtuw', 'fwoaty', 'fowmat', 'fwowzenset', 'gewtatties', 'gwobwals', 'haswatties', 'hush', 'hewlp', 'hexie', 'idy', 'inpuwt', 'inty', 'isyance', 'issubcwaas', 'itw', 'leny', 'wistie', 'wocals', 'mapy', 'maxx', 'memowyview', 'minnie', 'nextie', 'objwect', 'octy', 'owpen', 'owd', 'powie', 'pwint', 'pwopwty', 'wange', 'wepw', 'wevewse', 'woundie', 'setw', 'sewtatties', 'swice', 'sowted', 'statwmowd', 'stwie', 'swum', 'supw', 'tuwple', 'typie', 'vaws', 'ziwp']